/**
 * projecteuler.net
 * Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
#include <iostream>

const int cutoff = 4000000;

int return_if_even(int num) {
  return (num % 2 == 0) ? num : 0;
 }

int main(int argc, char *argv[]) {
  int sum = 2, fib = 0;
  int fib_seq[2] = { 1, 2 };
  while (fib <= cutoff)  {
    fib = fib_seq[0] + fib_seq[1];
    fib_seq[0] = fib_seq[1];
    fib_seq[1] = fib;
    if (fib > cutoff) break;

    sum += return_if_even(fib);
  }
  std::cout << "Sum: " << sum << std::endl;
  return 0;
}
